In [1]:
import pandas as pd

In [2]:
usage = pd.read_csv("../data/usage.csv")

In [3]:
usage

,city_name,routeno,routetp,startnodenm,endnodenm,startvehicletime,endvehicletime,intervaltime,intervalsattime,intervalsuntime,...,노선정류장수,노선거리(km),굴곡도,start,end,total_operating_time,interval_avg,num_bus,총인구수,노인(수)
0,창원시,1,마을버스,신전,창원역,540.0,2210.0,40.0,40.0,40.0,...,105,55.900000,2.0,340.000000,1330.000000,990.000000,40.000000,24,1003731,276574
1,창원시,2,마을버스,유등,창원역,725.0,2150.0,170.0,170.0,170.0,...,83,53.500000,1.7,445.000000,1310.000000,865.000000,170.000000,5,1003731,276574
2,창원시,3,마을버스,상리,진영시외주차장,750.0,1655.0,220.0,220.0,220.0,...,74,43.800000,2.6,470.000000,1015.000000,545.000000,220.000000,2,1003731,276574
3,창원시,7,마을버스,창원역,자여입구,620.0,2310.0,11.0,15.0,15.0,...,35,21.100000,1.0,380.000000,1390.000000,1010.000000,12.142857,83,1003731,276574
4,창원시,8,마을버스,창원역,삼성창원병원종점(8),600.0,2240.0,17.0,17.0,17.0,...,39,8.800000,1.8,360.000000,1360.000000,1000.000000,17.000000,58,1003731,276574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2442,합천군,660-1,농어촌(일반)버스,합천터미널,합천터미널,928.0,1614.0,128.1,114.6,118.0,...,27,29.863889,2.0,568.676575,974.532234,405.855659,124.728571,3,40756,23160
2443,합천군,670-2,농어촌(일반)버스,합천터미널,합천터미널,928.0,1614.0,128.1,114.6,118.0,...,27,29.863889,2.0,568.676575,974.532234,405.855659,124.728571,3,40756,23160
2444,합천군,810-3,농어촌(일반)버스,부림면정류장,합천터미널,928.0,1614.0,128.1,114.6,118.0,...,29,25.300000,1.3,568.676575,974.532234,405.855659,124.728571,3,40756,23160
2445,합천군,110-13,농어촌(일반)버스,부림면정류장,합천터미널,928.0,1614.0,128.1,114.6,118.0,...,27,29.863889,2.0,568.676575,974.532234,405.855659,124.728571,3,40756,23160
2446,합천군,120-7,농어촌(일반)버스,아막,박곡,928.0,1614.0,128.1,114.6,118.0,...,27,29.863889,2.0,568.676575,974.532234,405.855659,124.728571,3,40756,23160

### 도시 코드

In [4]:
city_code = pd.DataFrame([
    {"citycode":38010,"cityname":"창원시"},
    {"citycode":38030,"cityname":"진주시"},
    {"citycode":38050,"cityname":"통영시"},
    {"citycode":38060,"cityname":"사천시"},
    {"citycode":38070,"cityname":"김해시"},
    {"citycode":38080,"cityname":"밀양시"},
    {"citycode":38090,"cityname":"거제시"},
    {"citycode":38100,"cityname":"양산시"},
    {"citycode":38310,"cityname":"의령군"},
    {"citycode":38320,"cityname":"함안군"},
    {"citycode":38330,"cityname":"창녕군"},
    {"citycode":38340,"cityname":"고성군"},
    {"citycode":38350,"cityname":"남해군"},
    {"citycode":38360,"cityname":"하동군"},
    {"citycode":38370,"cityname":"산청군"},
    {"citycode":38380,"cityname":"함양군"},
    {"citycode":38390,"cityname":"거창군"},
    {"citycode":38400,"cityname":"합천군"}
    ])

In [5]:
usage = pd.merge(usage, city_code.rename(columns={"cityname" : "city_name"}), on="city_name", how="left")

### routeno -> routeid

In [6]:
import requests
import json
import pprint

# def routeno2id(city_code_, routeno_):
#     api_url = f"http://apis.data.go.kr/1613000/BusRouteInfoInqireService/getRouteNoList?serviceKey=J898%2Bzddf%2FpTsegkzSSN3hcgirJ2kkHIbj83qdZjeGTrfWWsvMErAuaux4iEO%2FidrxEJmr99O2IBbzKSk040DQ%3D%3D&_type=json&cityCode={city_code_}&routeNo={routeno_}"
#     response = requests.get(api_url)

#     # Check the response status code
#     if response.status_code == 200:
#         try:
#             result = json.loads(response.text)

#         except json.JSONDecodeError:
#             print("Error decoding JSON. Response content:", response.text)
#     else:
#         print(f"Request failed with status code {response.status_code}. Response content:", response.text)
    
#     if type(result["response"]["body"]["items"]["item"]) == dict:
#         item_ = result["response"]["body"]["items"]["item"]
#         if str(item_["routeno"]) == routeno_:
#             print(item_["routeid"])
#             return item_["routeid"]
#         else: 
#             print("error")
#     else:
#         for item_ in result["response"]["body"]["items"]["item"]:
#             if str(item_["routeno"]) == routeno_:
#                 print(item_["routeid"])
#                 return item_["routeid"]
#             else: 
#                 print("error")

In [7]:
df = pd.DataFrame()
for cc in city_code["citycode"].values:
    api_url = f"http://apis.data.go.kr/1613000/BusRouteInfoInqireService/getRouteNoList?serviceKey=J898%2Bzddf%2FpTsegkzSSN3hcgirJ2kkHIbj83qdZjeGTrfWWsvMErAuaux4iEO%2FidrxEJmr99O2IBbzKSk040DQ%3D%3D&numOfRows=10000&_type=json&cityCode={cc}"
    response = requests.get(api_url)

    # Check the response status code
    if response.status_code == 200:
        try:
            result = json.loads(response.text)

        except json.JSONDecodeError:
            print("Error decoding JSON. Response content:", response.text)
    else:
        print(f"Request failed with status code {response.status_code}. Response content:", response.text)
    # print(cc)
    # pprint.pprint(result["response"]["body"]["items"]["item"])
    
    _ = pd.DataFrame(result["response"]["body"]["items"]["item"])
    _["city_code"] = cc
    df = pd.concat([df, _])
    # print(df)

In [8]:
df["routeno"] = df["routeno"].astype(str)

In [9]:
usage = pd.merge(usage, df[["routeno", "routeid"]], on="routeno", how="left")

In [11]:
# usage.to_csv("../data/usage_id.csv", index=False)