In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import geopandas as gpd
import glob
import os
from shapely.geometry import Polygon
from shapely.geometry import Point

### 노인 인구 밀집 지역- 거제

In [2]:
gdf = gpd.read_file(
    "../data/경남 노인 인구 분포/거제시/nlsp_021001010.shp", 
    encoding="utf-8", 
    )
gdf['val'] = gdf['val'].fillna(0)
gdf = gdf[gdf["val"].apply(lambda x: x != 0.0)]
gdf = gdf.to_crs(epsg=5179)

In [3]:
gdf['point'] = gdf['geometry'].centroid.apply(lambda centroid: Point(centroid.x, centroid.y))

In [4]:
gdf

,gid,lbl,val,geometry,point
4,마라008419,7.00,7.0,"POLYGON ((1100800 1641900, 1100800 1642000, 11...",POINT (1100850 1641950)
6,마라044519,20.00,20.0,"POLYGON ((1104400 1651900, 1104400 1652000, 11...",POINT (1104450 1651950)
9,라라975559,26.00,26.0,"POLYGON ((1097500 1655900, 1097500 1656000, 10...",POINT (1097550 1655950)
10,마라087557,13.00,13.0,"POLYGON ((1108700 1655700, 1108700 1655800, 11...",POINT (1108750 1655750)
19,마라039555,15.00,15.0,"POLYGON ((1103900 1655500, 1103900 1655600, 11...",POINT (1103950 1655550)
...,...,...,...,...,...
4736,마라013550,62.00,62.0,"POLYGON ((1101300 1655000, 1101300 1655100, 11...",POINT (1101350 1655050)
4737,마라030547,31.00,31.0,"POLYGON ((1103000 1654700, 1103000 1654800, 11...",POINT (1103050 1654750)
4738,마라089563,19.00,19.0,"POLYGON ((1108900 1656300, 1108900 1656400, 11...",POINT (1108950 1656350)
4740,마라022581,9.00,9.0,"POLYGON ((1102200 1658100, 1102200 1658200, 11...",POINT (1102250 1658150)
4745,라라896510,6.00,6.0,"POLYGON ((1089600 1651000, 1089600 1651100, 10...",POINT (1089650 1651050)